apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: platform-nginx
  labels:
    app: guestbook
    tier: frontend
  name: guestbook-frontend-ingress
  namespace: platform
spec:
  rules:
  - host: platk8saas.dev.wx-d.net
    http:
      paths:
      - backend:
          serviceName: guestbook-frontend
          servicePort: 80
        path: {{ .Values.path }}